services:
  postgres:
    build:
      context: ./postgres
      dockerfile: dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
    networks:
      - testnet
    volumes:
      - db-data:/var/lib/postgresql/data:delegated

  fastapi:
    build:
      context: ./fastapi
      dockerfile: dockerfile
    ports:
      - '8001:8000'
    depends_on:
      - postgres
    networks:
      - testnet
    restart: unless-stopped

  serverless:
    build:
      context: ./serverless
      dockerfile: dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - fastapi
    networks:
      - testnet
    restart: unless-stopped

volumes:
  db-data:

networks:
  testnet:
    driver: bridge